export default {
  IS_FETCHING: "IS_FETCHING",
  GET_USERS: "GET_USERS",
  SET_USER: "SET_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
};